%YAML:1.0
cfg_avt_0: 0.35       #UtcSetDynParam(obj, dynamicParam.occlusion_thred)
cfg_avt_1: 0.38       #UtcSetDynParam(obj, dynamicParam.retry_acq_thred)
cfg_avt_2: 0.005       #UtcSetUpFactor(obj, up_factor)
cfg_avt_3: 10         #UtcSetIntervalFrame(obj, gapframe)
cfg_avt_4: 1          #UtcSetPLT_BS(obj, pltWork)
cfg_avt_5: 1          #UtcSetPLT_BS(obj, bsType)
cfg_avt_6: 80         #UtcSetRestraint(obj, resTraint.res_distance)
cfg_avt_7: 12000      #UtcSetRestraint(obj, resTraint.res_area)
cfg_avt_8: 1          #UtcSetEnhance(obj, enhEnable)
cfg_avt_9: 4.5        #UtcSetEnhfClip(obj, cliplimit)
cfg_avt_10: 1         #UtcSetBlurFilter(obj,FilterEnable)
cfg_avt_11: 1         #UtcSetPredict(obj, dictEnable)
cfg_avt_12: 8        #UtcSetMvPixel(obj, moveX)
cfg_avt_13: 5        #UtcSetMvPixel(obj, moveY)
cfg_avt_14: 5        #UtcSetMvPixel2(obj, moveX2)
cfg_avt_15: 5        #UtcSetMvPixel2(obj, moveY2)
cfg_avt_16: 500       #UtcSetSegPixelThred(obj, segPixelX)
cfg_avt_17: 400       #UtcSetSegPixelThred(obj, segPixelY)
cfg_avt_18: 10000     #UtcSetRoiMaxWidth(obj, maxValue);
cfg_avt_19: 1         #UtcSetBigSearch(obj, BigSecEnable)
cfg_avt_20: 1         #UtcSetExtSearch(obj, bExtSearch)
cfg_avt_21: 1         #UtcSetSceneMV(obj, bSceneMV)
cfg_avt_22: 80.0      #UtcSetTrkAngleThred(obj, trkAngleThred)
cfg_avt_23: 1         #UtcSetSechAxis(obj, bSearchAxis)
cfg_avt_24: 0         #UtcSetSechAxis(obj, bEstimateSearch)
cfg_avt_25: 0         #UtcSetTrajSechType(obj, trajSechType)
cfg_avt_26: 0         #UtcSetSimilarDetect(obj, bSimilarDetect)
cfg_avt_27: 0         #UtcSetPlatPanTilt(obj, panAng)
cfg_avt_28: 0         #UtcSetPlatPanTilt(obj, tiltAng)
cfg_avt_29: 0         #UtcSetPlatPanTilt(obj, panVel)
cfg_avt_30: 0         #UtcSetPlatPanTilt(obj, tiltVel)
cfg_avt_31: 60        #UtcSetFrameFreq(obj, framefreq)
cfg_avt_32: 0.1       #UtcSetUKFParam(obj, proc_noise_cov_xy)
cfg_avt_33: 0.01      #UtcSetUKFParam(obj, proc_noise_cov_vxvy)
cfg_avt_34: 0.5      #UtcSetUKFParam(obj, measure_noise_cov_xy)
cfg_avt_35: 1         #UtcSetTrajAnalysis(obj, bTrajAnalysis)
cfg_avt_36: 0         #UtcSetMultiModalDisp(obj, bMultiModalDisp)
cfg_avt_37: 1         #UtcSetSechValid(obj, bSechValid)
cfg_avt_38: 0         #UtcSetPrintTS(obj, bTrkPrintf)
cfg_avt_39: 0         #UtcSetPrintTS(obj, bScenePrintf)
cfg_avt_40: 0         #UtcSetPrintTS(obj, bSimPrintf)
cfg_avt_41: 0         #UtcSetSimilarThredType(obj, bSimPrintf)
cfg_avt_42: 20       #UtcSetDynamicTargetSize(UTCTRACK_OBJ *pUtcTrkObj, int minArea);
cfg_avt_43: 40000     #UtcSetDynamicTargetSize(UTCTRACK_OBJ *pUtcTrkObj, int maxArea);
cfg_avt_44: 0         #UtcSetDynTargetDetect(UTCTRACK_OBJ *pUtcTrkObj, bool bDynTargetDetect);
cfg_avt_45: 10000     #lossCoastTelapseMax (ms)
cfg_avt_46: 0         #reTrkStatFliterFrameCnt
