%YAML:1.0
ch00_font_filename: "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
ch00_font_size: 40
ch01_font_filename: "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
ch01_font_size: 40
##Front_font_filename: "/usr/share/fonts/truetype/abyssinica/simsun.ttc"
##Front_font_filename: "/usr/share/fonts/truetype/abyssinica/AbyssinicaSIL-R.ttf"
Front_font_filename: "./SIMSUN.TTC"
Front_font_size: 40


